language: scala
sudo: required
dist: trusty
group: edge

matrix:
  include:
    # Scala 2.12, JVM, JDK 11
    - jdk: openjdk11
      scala: 2.12.10
      env: COMMAND=ci-jvm
    # Scala 2.12, JavaScript
    - jdk: oraclejdk11
      scala: 2.12.10
      env: COMMAND=ci-js
    # Scala 2.13, JVM, JDK 11
    - jdk: openjdk11
      scala: 2.13.1
      env: COMMAND=ci-jvm
    # Scala 2.13, JavaScript
    - jdk: oraclejdk11
      scala: 2.13.1
      env: COMMAND=ci-js

install:
  - rvm use 2.6.5 --install --fuzzy
  - gem install jekyll -v 4

script:
  - sbt -J-Xmx6144m ++$TRAVIS_SCALA_VERSION $COMMAND

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete